#desde aqui corremos nuestro contenedor:

#primero definimos una etiqueta llamada servicios:
services:
  webserver:
    build: #le estamos diciendo que va ha construir este servicio.
      context: . #desde la carpeta que estoy ubicado.
      dockerfile: Dockerfile #y vas a buscar el archivo Dockerlie.
    volumes:
      - .:/app #esto sirve para enlazar el docker con el codigo y se vean los cambios inmediatamente
    ports:
      - "80:80" #unir el puerto local 80 con el puerto del contenedor 80.